### script to test url: built-in
### phpipam - create new address
---
- hosts: dns.bustraan.lab
  become: yes
  vars:
    - VM_name: testvm110
      #    - VM_IP: 192.168.1.159
    - pdns_server_ip: 192.168.1.247
    - pdns_api_pass: mypdnsapikey22
    - domain: bustraan.lab
    - ipaddr: 192.168.1.138
    - record_type: A

  tasks:
  - name: Check if {{ record_type }} record for {{ VM_name }} exist
    uri:
      method: GET
      url: "https://{{ pdns_server_ip }}/api/v1/servers/localhost/zones/\
            {{ domain }}"
      body_format: json
      headers:
        'X-API-Key': "{{ pdns_api_pass }}"
      return_content: true
      status_code:
        - 200
        - 404
      validate_certs: false
    register: pdns_record_check

  - name: Create {{ record_type }} record for {{ VM_name }}
    uri:
      method: PATCH
      url: "https://{{ pdns_server_ip }}/api/v1/servers/localhost/zones/\
            {{ domain }}"
      body:
        rrsets:
          - name: "{{ VM_name }}.{{ domain }}."
            type: "{{ record_type }}"
            ttl: 3600
            changetype: DELETE
            records:
              - content: "{{ ipaddr }}"
                disabled: false
            comments:
              - content: "Ansible managed IP"
                account: "Ansible"
      body_format: json
      headers:
        'X-API-Key': "{{ pdns_api_pass }}"
      return_content: true
      status_code:
        - 204
      validate_certs: false
    register: pdns_record
    when: >
      (pdns_record_check.json.rrsets |
      selectattr('name', 'match', VM_name + "." + domain ) | first)
      is defined
      or
      (pdns_record_check.json.rrsets |
      selectattr('name', 'match', VM_name + "." + domain) | first |
      json_query('records[0].content') == ipaddr)
    changed_when: >
      ((pdns_record_check.json.rrsets |
      selectattr('name', 'match', VM_name + "." + domain) | first)
      is defined
      or
      (pdns_record_check.json.rrsets |
      selectattr('name', 'match', VM_name + "." + domain) | first |
      json_query('records[0].content') == ipaddr))
      and
      "'OK' in pdns_record.msg"

  - name: Increase serial after adding entry
    shell: /usr/bin/pdnsutil increase-serial bustraan.lab

  - name: Restart pdns-recursor
    systemd:
      name: pdns-recursor
      state: restarted


