- name: 'Prepare proxmox hosts for automation'
  #hosts: 'pve1'
  vars_prompt:
  - name: VM_name
    prompt: "VM name"
    private: no
  - name: PV_node
    prompt: "pve1 or pve2"
    private: no
    default: pve1
    #  - name: VM_IP
    #prompt: "VM IP"
    #private: no
    #default: 192.168.1.190
  hosts: "{{ PV_node }}"
  user: root
  gather_facts: false
  roles:
    - { role: proxmox_deploy, default_proxmox_node: pve1 }
    - { role: pdns, hosts: dns.bustraan.lab }
